###
### $Release: $
### $Copyright: copyright(c) 2010 kuwata-lab.com all rights reserved $
### $License: MIT License $
###

task :default => :help

task :help do
  puts "help:"
  puts "  rake main    # print output"
end

desc "create *_.rb from *.html "
task :convert do
  sh "rbkwartzite -c 'View::%C_' -o 'view/%C_.rb' html/*.html"
end

desc "demonstration"
task :main => :convert do
  sh "ruby main.rb"
end

task :test => :convert do
  sh "ruby main.rb > output.actual"
  sh "diff -u output.expected output.actual"
  rm "output.actual"
end

require 'rake/clean'
CLEAN.include('*_.rb')
